### ISSUE TITLE
Maps refreshes and loses its state

### ISSUE THREAD

**Issue by AaronM04** [tobykurien/GoogleApps#16]
I am using v1.14 and I noticed that whenever I switch to another app or lock the screen, the Maps app forgets everything (zoom setting and position, and displaying of traffic). This makes it very difficult to use for checking traffic at stop lights to find the best route, which is my main use case.

Unrelated: two things I really like about this release are the ability to hide apps I don't use, and that Maps works again in this release. Keep up the good work! :)

**Comment by tobykurien** [comment]
Yep, app seems to loose it's state when switching out. I'll look into it.
