### ISSUE TITLE
Google Voice Play Voicemails

### ISSUE THREAD

**Issue by cwmke** [tobykurien/GoogleApps#17]
This app is just what I was looking for for youtube and Google Voice without having Google Play Services installed.  The only problem is that I can't play the audio of the voicemails from the app.  

I logged into Voice on Firefox and it appears they have an updated mobile site that allows the audio to be played from within the browser instead of attempting to download the audio to play on the device.  It would be great if the updated site could be used within GApps Browser.

Thanks a lot.

**Comment by tobykurien** [comment]
Unfortunately Google Voice isn't supported in my country, so it will be hard for me to fix this.

**Comment by cwmke** [comment]
I belive the url is https://www.google.com/voice/m.  I'm not sure if that's the same URL that you're using so I'm not really sure what brings up the new interface.  I just opened it with a couple different android user agents and it seems to bring up the new design.

**Comment by tobykurien** [comment]
That is the URL currently used in the app, so I am guessing it needs some 3rd party resources. One way to find what these are is to open the site in a desktop browser and monitor the network requests (in the developer tab) and see what the app needs access to. I unfortunately cannot do this since Voice isn't supported here.

**Comment by cwmke** [comment]
No problem.  I'll have a look tomorrow.

**Comment by cwmke** [comment]
Hi, I took a screenshot of the traffic.  Thanks for the suggestion.  The whited out areas are a list of what appear to be random, capitalized letters.  For example, DJWOIEUDFKLJDFS.

![screenshot_2015-02-05_14-16-02](https://cloud.githubusercontent.com/assets/1923967/6068486/16e566f4-ad42-11e4-9d75-809d9a5eac79.png)

**Comment by tobykurien** [comment]
Thanks for that. It looks like all requests go to www.google.com, which is already whitelisted, so I'm not sure what the problem could be.

**Comment by cwmke** [comment]
I'm not sure either.  Originally I thought maybe it was a user agent 
problem but I've tried a number of them both inside of the app and my 
browser and have not been able to reproduce the problem.

My best guess now is maybe it's something that's disabled or 
inaccessible within the browser?

Thanks for taking a look.

**Comment by cwmke** [comment]
The problem has resolved itself.  It appears Google is switching to the new interface on more devices now.  Thanks for the help.
