### ISSUE TITLE
New site request: hangouts

### ISSUE THREAD

**Issue by erasche** [tobykurien/GoogleApps#21]
It would be very helpful if hangouts was added to the list of supported URLs. (https://hangouts.google.com)

thanks!

**Comment by tobykurien** [comment]
That site just re-directs to the app on Play Store. As far as I can see, there is no hangouts mobi site.

**Comment by tobykurien** [comment]
Also, duplicate of this: https://github.com/tobykurien/GoogleApps/issues/18

**Comment by erasche** [comment]
Okay, thanks.
