### ISSUE TITLE
Add Fit and Translate

### ISSUE THREAD

**Issue by Almtesh** [tobykurien/GoogleApps#25]
Google Fit  and Translate are missing, is that possible to add them?

**Comment by tobykurien** [comment]
Yup they can be added, but you can also use them right now by going to the Search app and searching for "Google Fit" for example and clicking the webapp link. Google Fit does not seem to work as a webapp though.

**Comment by Almtesh** [comment]
How dumb I am, of course I can do that, I did not even think about this option.
Thanks.

**Comment by trymeouteh** [comment]
Please add translate.

**Comment by Almtesh** [comment]
And you can remove Google+.

**Comment by tobykurien** [comment]
Added translate, but fit just links to app on play store.
