### ISSUE TITLE
Google Play Music?

### ISSUE THREAD

**Issue by m52go** [tobykurien/GoogleApps#30]
Any way to include Google Play Music?

**Comment by tobykurien** [comment]
Does it work in the browser? What's the URL? You can get into it from GApps by going to Search and searching for it..

**Comment by m52go** [comment]
It's a bit strange.

On the desktop, Play Music is only available on the browser.

But on Android, they push you hard to use the native Android app (which feels _very_ similar to the web app). In Chrome, you're redirected to the Play Store. In Firefox, the desktop web interface shows (i.e., not responsive) but audio doesn't play (although the interface shows it's playing).

So anyway...I posted this partly to ask if you had any experience with this, and partly to see if others have a work-around / trick. 

If not, no worries, thanks so much for your work on it! It's invaluable to me for Google's other apps.

**Comment by mafrailea** [comment]
https://music.youtube.com works fine for me in Android browsers.

In fact, I've managed to open that URL inside the GApps Browser (by search for it in Google inside the app) and it works fine as well.

I think it could be a great additional and it would take very little effort to include. :)
