### ISSUE TITLE
Add Chrome Remote Desktop

### ISSUE THREAD

**Issue by VaclavPokorny** [tobykurien/GoogleApps#42]
I tried this through Google Search and it works nicely. It would be nice to have the Chrome Remote Desktop available as a selectable app. Please note, that it requires desktop user agent in order to work. An immersive fullscreen mode would also be great for this.

Homepage is: https://remotedesktop.google.com/access

**Comment by tobykurien** [comment]
I tried this but it just links to the app on Google play store.

**Comment by VaclavPokorny** [comment]
It doesn't if browser is in desktop mode, it probably needs desktop user agent.
