### ISSUE TITLE
Feature request: Hangouts

### ISSUE THREAD

**Issue by woodruffandtheschnibbleofazimuth** [tobykurien/GoogleApps#50]
Hello, i like the app and i think it's perfect to login on some Google Account without installing it on smartphone.
I think me and my old friend are the last men on Earth that still use Hangouts to chat.

Is it possible to add it as a service?

Thanks!

**Comment by tobykurien** [comment]
Does hangouts work in a browser? You can get to it in the app by searching for it from Google search and clickng the result

**Comment by woodruffandtheschnibbleofazimuth** [comment]
> Does hangouts work in a browser? You can get to it in the app by searching for it from Google search and clickng the result

Yes it works on browser but only on a desktop browser, on a mobile browser it forces me to download the app

**Comment by marcdw1289** [comment]
FYI, Hangouts can be used on mobile browsers if you switch the browser to desktop mode. The thing is that everything is super tiny. One would constantly be zooming in/out and scrolling about.
It's clear the Hangouts site does not have a mobile-friendly mode. GApps Browser probably would've had it included a long time ago if it were possible.
